<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Str;
use App\Mail\BloggerCreatedMail;

class BloggerManagementController extends Controller
{
    /**
     * Display listing of bloggers
     */
    public function index(Request $request)
    {
        $query = User::with('blogCategory')->where('user_type', 'bloger');

        // Apply search filter
        if ($request->filled('search')) {
            $search = $request->search;
            $query->where(function($q) use ($search) {
                $q->where('name', 'like', "%{$search}%")
                  ->orWhere('email', 'like', "%{$search}%")
                  ->orWhere('phone', 'like', "%{$search}%");
            });
        }

        $bloggers = $query->latest()->paginate(15);

        return view('admin.bloggers.index', compact('bloggers'));
    }

    /**
     * Show form for creating a blogger
     */
    public function create()
    {
        $categories = \App\Models\BlogCategory::active()->orderBy('name')->get();
        return view('admin.bloggers.create', compact('categories'));
    }

    /**
     * Store new blogger in database
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|string|max:255',
            'email' => 'required|email|unique:users,email',
            'phone' => 'required|string|max:20',
            'blog_category_id' => 'required|exists:blog_categories,id',
        ], [
            'email.unique' => 'This email is already registered on Mali Setu.',
            'blog_category_id.required' => 'Please select a blog category.',
            'blog_category_id.exists' => 'Selected category is invalid.',
        ]);

        try {
            // Custom autogenerated password: first 3 characters of Name + random Symbol + last 4 digits of Phone + random Number
            $cleanName = preg_replace('/[^A-Za-z]/', '', $request->name);
            $namePart = strtoupper(substr($cleanName, 0, 3));
            if (strlen($namePart) < 3) {
                $namePart = str_pad($namePart, 3, 'X');
            }

            $cleanPhone = preg_replace('/[^0-9]/', '', $request->phone);
            $phonePart = substr($cleanPhone, -4);
            if (strlen($phonePart) < 4) {
                $phonePart = str_pad($phonePart, 4, '0');
            }

            $symbols = ['@', '#', '$', '%', '*', '!'];
            $symbolPart = $symbols[array_rand($symbols)];

            $numberPart = rand(100, 999);

            $plainPassword = $namePart . $symbolPart . $phonePart . $numberPart;

            $blogger = User::create([
                'name' => $request->name,
                'email' => $request->email,
                'phone' => $request->phone,
                'password' => Hash::make($plainPassword),
                'user_type' => 'bloger',
                'blog_access' => true,
                'status' => 'active',
                'caste_verification_status' => 'approved', // Auto-approved to avoid restrictions
                'blog_category_id' => $request->blog_category_id,
            ]);

            // Dispatch credentials email
            Mail::to($blogger->email)->send(new BloggerCreatedMail($blogger, $plainPassword));

            return redirect()->route('admin.bloggers.index')
                ->with('success', "Blogger '{$blogger->name}' created successfully! Credentials emailed. Temporary password: {$plainPassword}");
        } catch (\Exception $e) {
            return back()->withErrors(['error' => 'Failed to create blogger: ' . $e->getMessage()])->withInput();
        }
    }

    /**
     * View blogger details
     */
    public function show($id)
    {
        $blogger = User::where('user_type', 'bloger')->findOrFail($id);
        
        // Fetch blogger's articles
        $blogs = \App\Models\Blog::where('user_id', $blogger->id)->latest()->get();

        return view('admin.bloggers.show', compact('blogger', 'blogs'));
    }

    /**
     * Show form for editing blogger details
     */
    public function edit($id)
    {
        $blogger = User::where('user_type', 'bloger')->findOrFail($id);
        $categories = \App\Models\BlogCategory::active()->orderBy('name')->get();
        return view('admin.bloggers.edit', compact('blogger', 'categories'));
    }

    /**
     * Update blogger details
     */
    public function update(Request $request, $id)
    {
        $blogger = User::where('user_type', 'bloger')->findOrFail($id);

        $request->validate([
            'name' => 'required|string|max:255',
            'email' => 'required|email|unique:users,email,' . $blogger->id,
            'phone' => 'required|string|max:20',
            'status' => 'required|in:active,suspended',
            'blog_category_id' => 'required|exists:blog_categories,id',
        ], [
            'blog_category_id.required' => 'Please select a blog category.',
            'blog_category_id.exists' => 'Selected category is invalid.',
        ]);

        try {
            $blogger->update([
                'name' => $request->name,
                'email' => $request->email,
                'phone' => $request->phone,
                'status' => $request->status,
                'blog_category_id' => $request->blog_category_id,
            ]);

            return redirect()->route('admin.bloggers.index')
                ->with('success', "Blogger '{$blogger->name}' updated successfully!");
        } catch (\Exception $e) {
            return back()->withErrors(['error' => 'Failed to update blogger: ' . $e->getMessage()])->withInput();
        }
    }

    /**
     * Delete blogger from database
     */
    public function destroy($id)
    {
        try {
            $blogger = User::where('user_type', 'bloger')->findOrFail($id);
            
            // Delete their published blogs
            \App\Models\Blog::where('user_id', $blogger->id)->delete();
            
            $blogger->delete();

            return redirect()->route('admin.bloggers.index')
                ->with('success', 'Blogger and their articles deleted successfully.');
        } catch (\Exception $e) {
            return redirect()->back()->with('error', 'Failed to delete blogger: ' . $e->getMessage());
        }
    }

    /**
     * Toggle status (active/suspended)
     */
    public function toggleStatus($id)
    {
        try {
            $blogger = User::where('user_type', 'bloger')->findOrFail($id);
            $newStatus = $blogger->status === 'active' ? 'suspended' : 'active';
            $blogger->update(['status' => $newStatus]);

            return response()->json([
                'success' => true,
                'status' => $newStatus,
                'message' => "Blogger status updated to " . ucfirst($newStatus)
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Check if email exists in database (AJAX)
     */
    public function checkEmail(Request $request)
    {
        $request->validate(['email' => 'required|email']);
        
        $email = $request->email;
        $excludeId = $request->input('exclude_id');

        $exists = User::where('email', $email)
            ->when($excludeId, function($q) use ($excludeId) {
                $q->where('id', '!=', $excludeId);
            })
            ->exists();

        return response()->json([
            'exists' => $exists
        ]);
    }
}
